server_info:
  name: freedom-server
  version: 3.0.0
  environment: local

server_keys: # Don't use this values in production environment
  public_key: |
    -----BEGIN PUBLIC KEY-----
    MCowBQYDK2VwAyEAoVQWbQbvR1XyCvxxyCPeuVVNGX+3An/HRKJNrzHXblM=
    -----END PUBLIC KEY-----
  private_key: |
    -----BEGIN PRIVATE KEY-----
    MC4CAQAwBQYDK2VwBCIEIJGX+J198uswHpxK8Cz6e4HEx26UxeOcm3oaHpKmn/bQ
    -----END PRIVATE KEY-----

smtp:
  host: smtp_dummy_host
  port: smtp_dummy_port
  user: smtp_dummy_user
  password: smtp_dummy_pass
  tls: true

redis:
  host: localhost
  port: 6379
  password: